autoscale_instance_shape = "VM.Standard2.1"
region = "ap-sydney-1"
instance_count = 1
instance_shape = "VM.Standard2.1"
availability_domain = "1"
admin_subnet = "0.0.0.0/0"
assign_public_ip_instance = "true"
hostname = "my.host.com"
customer_network= "172.0.0.0/16"
